# ##############################################################################
# # File: config.yaml                                                          #
# # Project: app                                                               #
# # Created Date: 2023/09/10 23:19:21                                          #
# # Author: realjf                                                             #
# # -----                                                                      #
# # Last Modified: 2023/09/11 12:54:59                                         #
# # Modified By: realjf                                                        #
# # -----                                                                      #
# # Copyright (c) 2023 realjf                                                  #
# ##############################################################################


frontend:
  title: "E-book conversion tool"
  ID: "realjf.com"

backend:
  log:
    level: "debug"
